### ISSUE TITLE
Unable to use custom validators with micro configs

### ISSUE THREAD

**Issue by Shatnerz** [robertchase/rhc#26]
Based on this

    raise Exception("validate must be one of 'int', 'bool', 'file'")

we are limited to 3 validators. If we wanted to parse a string into a something like a date or datetime object we would have to do that every time we access that value which is an added pain.

This is possible in the older style where the config is just stored as `config.py`

**Comment by robertchase** [comment]
micro file `CONFIG` now accepts a custom validator. specify the full path to the function, relative to `PYTHONPATH`, as a dot-separated string.
